### ISSUE TITLE
Missing slash when nginx open file

### ISSUE THREAD

**Issue by chikei** [YuMS/gitlab-ce-pages#16]
This [commit](https://github.com/YuMS/gitlab-ce-pages/commit/988154c706f87e851500ef5950a21d0698c710b8) seems causing plain setting (empty cname.txt, no RELATIVE_URL) missing a slash such that when navigating `{GITLAB_CE_PAGE_URL}/{WORKSPACE}/{PROJECT_NAME}` nginx try to open `/home/pages/public{WORKSPACE}/{PROJECT_NAME}` instead of `/home/pages/public/{WORKSPACE}/{PROJECT_NAME}`.
When using 1.3.0, everything is fine.

**Comment by YuMS** [comment]
Thank you. I didn't add tests for this most fundamental function. And here I screwed things up.
Bug confirmed and fixed in 8a76e61, please update to `1.3.2`.
