### ISSUE TITLE
feature request "overview page"

### ISSUE THREAD

**Issue by niklas-dahl** [YuMS/gitlab-ce-pages#22]
hey awesome project and an additional thanks for wrapping it all in a docker container for convenience :)

It would be awesome if this thing had an overview page just like the other gitlab pages project you mentioned in your Reamde: https://github.com/Glavin001/GitLab-Pages

Just simply to see which projects you have access to and to automatically create the webhooks is a big time saver when you want to use this on 20+ projects.

Thanks.

**Comment by YuMS** [comment]
I've checked the APIs and found something like

- https://docs.gitlab.com/ee/api/oauth2.html for OAuth2
- https://docs.gitlab.com/ee/api/projects.html#list-owned-projects for listing owned projects
- https://docs.gitlab.com/ee/api/projects.html#add-project-hook for adding project hook
- https://docs.gitlab.com/ee/api/projects.html#list-project-hooks for listing project hooks


But I'm writing my thesis so currently don't have time. Contribution welcomed.

**Comment by niklas-dahl** [comment]
since the project itself is more or less deprecated I'm closing this.

Thanks again for an awesome solution until now.
