### ISSUE TITLE
Error after Build

### ISSUE THREAD

**Issue by pree** [YuMS/gitlab-ce-pages#3]
Hey,

Gitlab-CE-Pages is working fine, but I get an Error after the import is done. Log from `docker attach`:

``` bash
options { url: 'https://gitlab-domain/api/v3/projects/53/builds/398/artifacts',
  headers: { 'PRIVATE-TOKEN': 'thisissecret' } }
398.zip downloaded
unzipped 398.zip into /home/pages/public/Group/Project
removing artifact /home/pages/public/398.zip
moving files out of public
artifact removal /home/pages/public/398.zip succeed
files moving out of public failed
{ Error: Command failed: cd /home/pages/public/Group/Project && mv public PROJECT_ROOT && cd PROJECT_ROOT && mv ./* .. && cd .. && rm -rf PROJECT_ROOT
mv: cannot stat 'public': No such file or directory

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cd /home/pages/public/Group/Project && mv public PROJECT_ROOT && cd PROJECT_ROOT && mv ./* .. && cd .. && rm -rf PROJECT_ROOT' }
```

**Comment by YuMS** [comment]
It seems that the structure of artifact generated in your project is not standard. Specifically, it lacks a containing folder named `public`.

This setting is for GCP to be compatible with official GitLab Pages.

You may want to refer to some example from official GitLab Pages: https://gitlab.com/pages/hugo/blob/master/.gitlab-ci.yml .

I guess adding this in your `.gitlab-ci.yml` will do

```
  artifacts:
    paths:
    - public
```

**Comment by pree** [comment]
Hey YuMS, 

thanks for the response. Yes I'm missing the public folder, didn't know it was neccessary. 

Gonna test it latet with a public folder

Best Regards, 
Schizopriest

**Comment by pree** [comment]
Just tried it and it is working fine now.
Output of `docker attach`

``` bash
options { url: 'https://gitlab-domain/api/v3/projects/53/builds/414/artifacts',
  headers: { 'PRIVATE-TOKEN': 'thisissecret' } }
414.zip downloaded
unzipped 414.zip into /home/pages/public/Group/Project
removing artifact /home/pages/public/414.zip
moving files out of public
artifact removal /home/pages/public/414.zip succeed
files moving out of public succeed
```

You could include the GItLab Pages Documentation into your README to reference to the .gitlab-ci.yml formats http://docs.gitlab.com/ee/pages/README.html

Best Regards,
Schizopriest

**Comment by pree** [comment]
#4
