### ISSUE TITLE
Add the ability to include custom nginx configurations

### ISSUE THREAD

**Issue by webpigeon** [YuMS/gitlab-ce-pages#9]
Thank you for making this, it's a feature that has been missing from gitlab-ce for a long time and it works really well.

It would be really cool if you could include custom nginx configuration via one of the volumes. My use case for this is the ability to add more advanced rewrite rules such as:

```
server {
  server_name ~^(.*)\.example\.com$ ;
  root /home/pages/public/$1/homepage;
}
```

so that people can access either `pages.example.org/username/project` or access a user's static homepage via `username.example.com`. This is simliar to how the github user repositries work (ie. create a repository named `<username>.gitlab.io` to deploy a static 'portfolio` site.

**Comment by webpigeon** [comment]
I'm looking at doing this in our fork - I'll make a pull request when I've tested it :)
https://github.com/unitycoders/gitlab-ce-pages

**Comment by YuMS** [comment]
Great idea! And thank you for your support!

I'm thinking that is it possible that in current version, putting

```
~^(.*)\.example\.com$ $1/homepage
```

into `cnames.txt` could fit your need?

**Comment by webpigeon** [comment]
Would that work? It would be extremely user friendly if it did (much cleaner than my solution).

I looked though the source and thought it wouldn't (just looked again at the generate-sites.sh file and it looks like it should do). I'll give it a go :+1: 

(I'll keep working on support for custom nginx blocks, it might still be handy for things like SSL support)

**Comment by YuMS** [comment]
@webpigeon wildcard CNAME is now supported in `1.3.0`.

In my old comment https://github.com/YuMS/gitlab-ce-pages/issues/9#issuecomment-250108494, I mistakenly flipped server name and project name. So make sure to refer to README.

**Comment by YuMS** [comment]
Close because allowing arbitrary nginx configurations may introduce many unpredictable issues. New features should be added when they can be clearly described, at least for now.
